# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29b542394e865600a719f6885a2df70c4d21380c64184ff3fbde5d65d26e13094086eff2425ead5dfd3ec5a95ee00898983e6260dc2b96ea8dc675ef72750e84

test:
  secret_key_base: f8b54122365b3e99dab5e42cb45089ceab6c01920cacb1683c7dad547cc1f6e9a7db3cdfc9746a0d016a5b62a8a2359de54e354e322ccf337aeb06b66b87643d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
